select 
  ? AS VERSION,
  UTCM.OWNER AS OWNER,
  UTCM.TABLE_NAME AS TABLENAME,
  UTCM.COMMENTS AS TABLECOMMENTS,
  UCCM.COLUMN_NAME AS COLUMNNAME,
  UCCM.COMMENTS AS COLUMNCOMMENTS,
  CASE WHEN PK.COLUMN_NAME IS NULL 
    THEN 'N'
    ELSE 'Y'
  END AS ISPK,
  DATA_TYPE AS DATATYPE,
  DATA_LENGTH AS DATALENGTH,
  DATA_PRECISION AS DATAPRECISION,
  DATA_SCALE AS DATASCALE,
  UTCL.COLUMN_ID AS COLUMNID,
  UTCL.NULLABLE AS NULLABLE,
  UTCL.CHAR_USED AS CHARUSED,
  UTCL.CHAR_LENGTH AS CHARLENGTH
FROM
  ALL_TAB_COMMENTS UTCM,
  ALL_TAB_COLUMNS UTCL,
  ALL_col_comments UCCM, 
  (	
  	SELECT 
		  UCC.TABLE_NAME,
		  UCC.COLUMN_NAME
		FROM 
		  ALL_CONS_COLUMNS UCC,
		  (SELECT 
			    TABLE_NAME,
			    CONSTRAINT_NAME ,
			    OWNER
			  FROM ALL_CONSTRAINTS  
			  WHERE CONSTRAINT_TYPE = 'P' 
	      	  AND OWNER = ?
        AND
            TABLE_NAME not like '%$%'  
      		) P
	WHERE  
		  P.CONSTRAINT_NAME = UCC.CONSTRAINT_NAME
	AND
	  P.TABLE_NAME = UCC.TABLE_NAME
  AND 
    UCC.OWNER = P.OWNER
	) PK
WHERE
  UTCM.OWNER = ?
AND  
  UTCM.TABLE_NAME 	= UTCL.TABLE_NAME
AND  
  UTCM.OWNER  		= UTCL.OWNER
AND
  UCCM.COLUMN_NAME 	= UTCL.COLUMN_NAME
AND
  UCCM.TABLE_NAME 	= UTCL.TABLE_NAME  
AND
  UCCM.OWNER = UTCL.OWNER      
AND
  UTCL.TABLE_NAME = PK.TABLE_NAME(+)
AND
	UTCL.COLUMN_NAME = PK.COLUMN_NAME(+) 
AND
	 UTCL.TABLE_NAME not like '%$%'
ORDER BY 
	TABLENAME ,ISPK ,COLUMNNAME
  